name:"generator"
acthor:"wiam abd"
description:"generates"
runs:
  using: "docker"
  image: "Dockerfile"
branding: 
  icon:"git-branch"
  colore:"red"
inputs:
  email:
    description: the commiter's email address
    required: True
    default: ${{ github.acthor}}@localhost
  name:
    description: The commitier's name 
    required: True
    default: ${{github.acthor}}