name:"generator"
aucthor:"wiam abd"
description:"generates"
runs:
  using: "docker"
  image: "Dockerfile"
branding: 
  icon:"git-branch"
  color:"red"
inputs:
  email:
    description: the committer's email address
    required: True
    default: ${{ github.aucthor}}@localhost
  name:
    description: The committier's name 
    required: True
    default: ${{github.aucthor}}